### PR TITLE
Add FAQ on shm-size and add Dockerfile setuptools upgrade

### PR DESCRIPTION
**Pull request by ntadimeti**

### CODE REVIEW

**Comment by tijyojwad** [comment]
@ntadimeti can you also upload this dockerfile to dockerhub?

**Comment by ntadimeti** [comment]
@tijyojwad I think Dockerfile is only shown on docker hub if we hookup our github account and trigger automatic builds from dockerhub : https://stackoverflow.com/questions/54435543/how-to-upload-dockerfile-to-dockerhub

Correct me if I'm missing something

**Comment by tijyojwad** [comment]
My apologies, I meant can you upload the docker image associated with this fixed up dockerfile to the hub

**Comment by ntadimeti** [comment]
The docker image associated with these changes is already uploaded with latest and 0.2.0 tags. These changes were made inorder to upload those images around a month ago :)

**Pull request merged**
